version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
   configuration: docs/source/conf.py
   builder: html
   fail_on_warning: false

python:
   install:
     - method: pip
       path: .
     - requirements: requirements.txt
     - requirements: docs/requirements.txt
