"""Add Strategy name

Revision ID: 6ceefa71dc90
Revises: 9137d93c2926
Create Date: 2022-02-02 15:25:47.878861

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel  # NEW
import sqlmodel.sql.sqltypes  # NEW


# revision identifiers, used by Alembic.
revision = '6ceefa71dc90'
down_revision = '9137d93c2926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategybackup', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategybackup', 'name')
    # ### end Alembic commands ###
