"""Add strategy_hash fields

Revision ID: 9137d93c2926
Revises: 53e77a272071
Create Date: 2022-02-02 15:22:25.488987

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel  # NEW
import sqlmodel.sql.sqltypes  # NEW


# revision identifiers, used by Alembic.
revision = '9137d93c2926'
down_revision = '53e77a272071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtestreport', sa.Column('strategy_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_backtestreport_strategy_hash'), 'backtestreport', ['strategy_hash'], unique=False)
    op.add_column('hyperoptreport', sa.Column('strategy_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_hyperoptreport_strategy_hash'), 'hyperoptreport', ['strategy_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hyperoptreport_strategy_hash'), table_name='hyperoptreport')
    op.drop_column('hyperoptreport', 'strategy_hash')
    op.drop_index(op.f('ix_backtestreport_strategy_hash'), table_name='backtestreport')
    op.drop_column('backtestreport', 'strategy_hash')
    # ### end Alembic commands ###
