"""Alter strategybackup text field

Revision ID: b9fc1ff6b2ff
Revises: 6ceefa71dc90
Create Date: 2022-02-02 15:26:59.736823

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel  # NEW
import sqlmodel.sql.sqltypes  # NEW


# revision identifiers, used by Alembic.
revision = 'b9fc1ff6b2ff'
down_revision = '6ceefa71dc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategybackup_text', table_name='strategybackup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_strategybackup_text', 'strategybackup', ['text'], unique=False)
    # ### end Alembic commands ###
